CREATE TABLE eros_vehicles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nickname TEXT NOT NULL,
    year INTEGER NOT NULL,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    color TEXT NOT NULL
);

-- ALTER TABLE eros_garage
--     ADD COLUMN
--     vehicle_id INTEGER REFERENCES eros_vehicles(id)
--     ON DELETE SET NULL;